using Inventory.Data.Models;
using KoalaInventoryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Inventory.Data.Data_Seeds
{
    public static class ProductsSeed
    {
        public static List<Product> Products { get; set; } = new List<Product>()
        {
            new Product() { Id = 1, Name = "Saudi Arabia Flag", Description = "High-quality Saudi Arabia flag for display", Price = 804, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 2, Name = "Textbook - Mathematics", Description = "Comprehensive textbook for Mathematics", Price = 394, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 3, Name = "Laptop", Description = "Powerful laptop for home and office use", Price = 740, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 4, Name = "TV - 40 Inch", Description = "Slim and stylish 40-inch smart TV", Price = 72, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 5, Name = "Garden Tools Set", Description = "Essential garden tools set for outdoor tasks", Price = 490, SupplierId = 4, CategoryId = 1 },
            new Product() { Id = 6, Name = "Smartphone - Pro Edition", Description = "High-performance smartphone with a large display", Price = 113, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 7, Name = "Leather Sofa", Description = "Elegant leather sofa for living room", Price = 607, SupplierId = 5, CategoryId = 1 },
            new Product() { Id = 8, Name = "Portable Power Bank", Description = "Fast-charging power bank for mobile devices", Price = 664, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 9, Name = "Digital Camera", Description = "Compact digital camera with high resolution", Price = 99, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 10, Name = "Wooden Dining Table", Description = "Solid wood dining table with modern design", Price = 833, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 11, Name = "Palestine Flag", Description = "National Palestine flag for home and events", Price = 9, SupplierId = 1, CategoryId = 1 },
            new Product() { Id = 12, Name = "Egypt Flag", Description = "Flag of Egypt, durable and fade-resistant", Price = 8, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 13, Name = "Flag of Saudi Arabia", Description = "Premium Saudi Arabia flag for outdoor use", Price = 10, SupplierId = 3, CategoryId = 1 },
            new Product() { Id = 14, Name = "Gaming Laptop", Description = "High-end gaming laptop with advanced graphics", Price = 500, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 15, Name = "Smartphone - Mini Edition", Description = "Compact smartphone with essential features", Price = 300, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 16, Name = "Tablet - 10 Inch", Description = "10-inch tablet with large display and fast processor", Price = 200, SupplierId = 3, CategoryId = 2 },
            new Product() { Id = 17, Name = "Refrigerator - Double Door", Description = "Spacious double door refrigerator", Price = 800, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 18, Name = "Washing Machine", Description = "Energy-efficient washing machine", Price = 600, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 19, Name = "Microwave Oven", Description = "Compact microwave oven with multiple settings", Price = 150, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 20, Name = "Modern Sofa", Description = "Stylish and comfortable modern sofa", Price = 350, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 21, Name = "Classic Dining Table", Description = "Classic dining table for six", Price = 450, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 22, Name = "Bed Frame - Queen Size", Description = "Sturdy queen-size bed frame", Price = 400, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 23, Name = "Novel - Fiction", Description = "Fiction novel by a best-selling author", Price = 15, SupplierId = 1, CategoryId = 5 },
            new Product() { Id = 24, Name = "Cookbook - Healthy Recipes", Description = "Collection of healthy recipes", Price = 20, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 25, Name = "Science Textbook", Description = "Educational science textbook for students", Price = 30, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 26, Name = "LCD Monitor", Description = "High-resolution LCD monitor for desktop", Price = 180, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 27, Name = "Wardrobe - 3 Door", Description = "Spacious 3-door wardrobe for bedrooms", Price = 615, SupplierId = 1, CategoryId = 1 },
            new Product() { Id = 28, Name = "Wall Mirror", Description = "Decorative wall mirror for living room", Price = 563, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 29, Name = "Cookbook - Quick Meals", Description = "Cookbook with quick and easy meal recipes", Price = 243, SupplierId = 3, CategoryId = 2 },
            new Product() { Id = 30, Name = "Electric Heater", Description = "Portable electric heater for home", Price = 5, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 31, Name = "Kitchen Rug", Description = "Soft kitchen rug with non-slip backing", Price = 336, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 32, Name = "Steam Iron", Description = "Powerful steam iron for wrinkle-free clothes", Price = 874, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 33, Name = "Game Theory Textbook", Description = "Textbook on game theory and applications", Price = 436, SupplierId = 2, CategoryId = 3 },
            new Product() { Id = 34, Name = "Curved Monitor", Description = "Large curved monitor for immersive experience", Price = 927, SupplierId = 3, CategoryId = 3 },
            new Product() { Id = 35, Name = "Leather Sofa - 3 Seater", Description = "Comfortable leather sofa for three people", Price = 201, SupplierId = 5, CategoryId = 4 },
            new Product() { Id = 36, Name = "Cookbook - Baking Essentials", Description = "Essential cookbook for baking recipes", Price = 399, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 37, Name = "Egypt Flag", Description = "Durable Egypt flag for all occasions", Price = 549, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 38, Name = "Laptop - Kid's Edition", Description = "Durable laptop for children's learning", Price = 442, SupplierId = 3, CategoryId = 3 },
            new Product() { Id = 39, Name = "Bed Frame - King Size", Description = "Elegant king-size bed frame", Price = 657, SupplierId = 5, CategoryId = 1 },
            new Product() { Id = 40, Name = "USB Charger", Description = "Fast USB charger for multiple devices", Price = 257, SupplierId = 3, CategoryId = 2 },
            new Product() { Id = 41, Name = "Convertible Tablet", Description = "Convertible tablet for mobile and desktop use", Price = 639, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 42, Name = "Noise Cancelling Headphones", Description = "Headphones with noise-cancelling feature", Price = 676, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 43, Name = "Extendable Dining Table", Description = "Extendable dining table for extra seating", Price = 161, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 44, Name = "Palestine Flag - Mini", Description = "Miniature Palestine flag for display", Price = 9, SupplierId = 1, CategoryId = 1 },
            new Product() { Id = 45, Name = "Lebanon Flag", Description = "High-quality Lebanon flag", Price = 10, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 46, Name = "USA Flag", Description = "Durable USA flag for outdoor use", Price = 12, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 47, Name = "China Flag", Description = "Quality China flag for display", Price = 8, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 48, Name = "Brazil Flag", Description = "Vibrant Brazil flag for all occasions", Price = 11, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 49, Name = "Germany Flag", Description = "Germany flag for international events", Price = 10, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 50, Name = "France Flag", Description = "Classic France flag for outdoor use", Price = 9, SupplierId = 2, CategoryId = 3 },
            new Product() { Id = 51, Name = "UK Flag", Description = "United Kingdom flag for all seasons", Price = 13, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 52, Name = "Russia Flag", Description = "Durable Russia flag for display", Price = 9, SupplierId = 4, CategoryId = 1 },
            new Product() { Id = 53, Name = "Italy Flag", Description = "High-quality Italy flag for indoor and outdoor use", Price = 10, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 54, Name = "USB Flash Drive", Description = "Portable USB flash drive with 16GB capacity", Price = 50, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 55, Name = "Notebook - A5 Size", Description = "Compact notebook for notes and ideas", Price = 12, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 56, Name = "Fitness Wristband", Description = "Smart fitness wristband for activity tracking", Price = 20, SupplierId = 4, CategoryId = 5 },
            new Product() { Id = 57, Name = "Palestine Flag - Large", Description = "Large Palestine flag for official events", Price = 9, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 58, Name = "Bluetooth Speaker", Description = "Portable Bluetooth speaker with deep bass", Price = 40, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 59, Name = "Desk Calendar", Description = "Compact desk calendar for office use", Price = 18, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 60, Name = "Wireless Headphones", Description = "Comfortable wireless headphones with long battery life", Price = 65, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 61, Name = "Baseball Cap", Description = "Classic baseball cap with adjustable strap", Price = 15, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 62, Name = "Insulated Water Bottle", Description = "Stainless steel insulated water bottle", Price = 25, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 63, Name = "Wall Poster - Art", Description = "Artistic wall poster for home decoration", Price = 8, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 64, Name = "Palestine Flag - Small", Description = "Small Palestine flag for personal use", Price = 10, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 65, Name = "Ceramic Coffee Mug", Description = "Durable ceramic coffee mug for office or home", Price = 15, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 66, Name = "Jordan Flag", Description = "Jordan flag with vibrant colors", Price = 8, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 67, Name = "Metal Keychain", Description = "Durable metal keychain with modern design", Price = 5, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 68, Name = "Polarized Sunglasses", Description = "Polarized sunglasses for UV protection", Price = 25, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 69, Name = "Graphic T-Shirt", Description = "Comfortable graphic t-shirt with unique design", Price = 18, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 70, Name = "Hardcover Notebook", Description = "Durable hardcover notebook for everyday use", Price = 12, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 71, Name = "Leather Bracelet", Description = "Stylish leather bracelet for daily wear", Price = 20, SupplierId = 4, CategoryId = 5 },
            new Product() { Id = 72, Name = "Laptop Decal Sticker", Description = "Customizable laptop sticker for decoration", Price = 7, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 73, Name = "Ballpoint Pen", Description = "Smooth writing ballpoint pen", Price = 6, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 74, Name = "Noise-Cancelling Headphones", Description = "Premium noise-cancelling headphones", Price = 50, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 75, Name = "Portable Bluetooth Speaker", Description = "Compact Bluetooth speaker for outdoor use", Price = 55, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 76, Name = "Reusable Water Bottle", Description = "Eco-friendly reusable water bottle", Price = 20, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 77, Name = "Framed Poster", Description = "Framed wall poster for home decor", Price = 10, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 78, Name = "Silicone Phone Case", Description = "Protective silicone phone case", Price = 15, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 79, Name = "Travel Backpack", Description = "Spacious travel backpack with multiple compartments", Price = 30, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 80, Name = "Smartwatch - Fitness Edition", Description = "Fitness smartwatch with health tracking features", Price = 80, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 81, Name = "Travel Duffel Bag", Description = "Durable duffel bag for travel", Price = 35, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 82, Name = "Portable Power Bank - Slim", Description = "Slim power bank with fast charging", Price = 25, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 83, Name = "High-Speed Flash Drive", Description = "High-speed USB flash drive with 32GB capacity", Price = 10, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 84, Name = "Desktop Calendar", Description = "Compact desktop calendar for office use", Price = 8, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 85, Name = "Ergonomic Mouse Pad", Description = "Comfortable mouse pad with wrist support", Price = 12, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 86, Name = "Fast Charging Charger", Description = "Fast charging USB charger for multiple devices", Price = 15, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 87, Name = "Silicone Wristband", Description = "Durable silicone wristband for everyday wear", Price = 10, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 88, Name = "Syria Flag", Description = "Quality Syria flag for events", Price = 9, SupplierId = 3, CategoryId = 1 },
            new Product() { Id = 89, Name = "Compact Umbrella", Description = "Portable umbrella for travel", Price = 12, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 90, Name = "Lebanon Flag - Small", Description = "Small Lebanon flag for personal use", Price = 7, SupplierId = 5, CategoryId = 1 },
            new Product() { Id = 91, Name = "Office Desk Organizer", Description = "Multi-functional desk organizer for office supplies", Price = 18, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 92, Name = "Art Wall Poster", Description = "High-quality art poster for home decor", Price = 9, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 93, Name = "Bluetooth Over-Ear Headphones", Description = "Comfortable Bluetooth over-ear headphones", Price = 55, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 94, Name = "Custom Keychain", Description = "Personalized keychain with durable metal", Price = 5, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 95, Name = "Smartwatch - Luxury Edition", Description = "Luxury smartwatch with premium features", Price = 90, SupplierId = 5, CategoryId = 4 },
            new Product() { Id = 96, Name = "Rollerball Pen", Description = "Smooth writing rollerball pen", Price = 6, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 97, Name = "Academic Notebook", Description = "Durable academic notebook for school and office", Price = 14, SupplierId = 3, CategoryId = 1 },
            new Product() { Id = 98, Name = "Summer Cap", Description = "Breathable summer cap with adjustable strap", Price = 12, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 99, Name = "Polarized Sunglasses - Black", Description = "Polarized sunglasses with black frame", Price = 25, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 100, Name = "Charm Bracelet", Description = "Stylish charm bracelet for daily wear", Price = 20, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 101, Name = "Protective Phone Case", Description = "Durable protective case for smartphones", Price = 15, SupplierId = 2, CategoryId = 3 },
            new Product() { Id = 102, Name = "Travel Backpack", Description = "Spacious and ergonomic travel backpack", Price = 32, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 103, Name = "Insulated Water Bottle", Description = "Double-walled insulated water bottle", Price = 18, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 104, Name = "Wireless Laptop Keyboard", Description = "Wireless keyboard compatible with all laptops", Price = 6, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 105, Name = "Fast Charging Phone Charger", Description = "High-speed phone charger with universal compatibility", Price = 16, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 106, Name = "USB Flash Drive", Description = "64GB high-speed USB flash drive", Price = 12, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 107, Name = "Leather Wristband", Description = "Elegant leather wristband for men and women", Price = 11, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 108, Name = "Desktop Calendar", Description = "Stylish desktop calendar with monthly pages", Price = 8, SupplierId = 4, CategoryId = 1 },
            new Product() { Id = 109, Name = "Gel Ink Pen", Description = "Smooth-writing gel ink pen for office use", Price = 7, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 110, Name = "Expandable Travel Bag", Description = "Lightweight expandable travel bag", Price = 36, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 111, Name = "Journal Notebook", Description = "Classic journal notebook for writing and notes", Price = 13, SupplierId = 2, CategoryId = 1 }
        };
    }
}
