using KoalaInventoryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Inventory.Data.Data_Seeds
{
    public static class ProductsSeed
    {
        public static List<Product> Products { get; set; } = new List<Product>()
        {
            new Product() { Id = 1, Name = "Saudi Arabia Flag", Description = "Automotive Products", Price = 804, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 2, Name = "Textbook", Description = "Toys", Price = 394, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 3, Name = "Laptop", Description = "Home Appliances", Price = 740, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 4, Name = "TV", Description = "Beauty Products", Price = 72, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 5, Name = "Saudi Arabia Flag", Description = "Garden Equipment", Price = 490, SupplierId = 4, CategoryId = 1 },
            new Product() { Id = 6, Name = "Smartphone", Description = "Furniture", Price = 113, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 7, Name = "Sofa", Description = "Electronics Products", Price = 607, SupplierId = 5, CategoryId = 1 },
            new Product() { Id = 8, Name = "Power Bank", Description = "Books", Price = 664, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 9, Name = "Camera", Description = "Electronics Products", Price = 99, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 10, Name = "Dining Table", Description = "Sports Equipment", Price = 833, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 11, Name = "Palestine Flag", Description = "Flags Products", Price = 9, SupplierId = 1, CategoryId = 1 },
            new Product() { Id = 12, Name = "Egypt Flag", Description = "Flags Products", Price = 8, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 13, Name = "Saudi Arabia Flag", Description = "Flags Products", Price = 10, SupplierId = 3, CategoryId = 1 },
            new Product() { Id = 14, Name = "Laptop", Description = "Electronics Products", Price = 500, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 15, Name = "Smartphone", Description = "Electronics Products", Price = 300, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 16, Name = "Tablet", Description = "Electronics Products", Price = 200, SupplierId = 3, CategoryId = 2 },
            new Product() { Id = 17, Name = "Refrigerator", Description = "Home Appliances", Price = 800, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 18, Name = "Washing Machine", Description = "Home Appliances", Price = 600, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 19, Name = "Microwave", Description = "Home Appliances", Price = 150, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 20, Name = "Sofa", Description = "Furniture", Price = 350, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 21, Name = "Dining Table", Description = "Furniture", Price = 450, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 22, Name = "Bed Frame", Description = "Furniture", Price = 400, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 23, Name = "Novel", Description = "Books", Price = 15, SupplierId = 1, CategoryId = 5 },
            new Product() { Id = 24, Name = "Cookbook", Description = "Books", Price = 20, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 25, Name = "Textbook", Description = "Books", Price = 30, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 26, Name = "Monitor", Description = "Furniture", Price = 180, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 27, Name = "Wardrobe", Description = "Beauty Products", Price = 615, SupplierId = 1, CategoryId = 1 },
            new Product() { Id = 28, Name = "Mirror", Description = "Toys", Price = 563, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 29, Name = "Cookbook", Description = "Electronics Products", Price = 243, SupplierId = 3, CategoryId = 2 },
            new Product() { Id = 30, Name = "Heater", Description = "Flags Products", Price = 5, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 31, Name = "Rug", Description = "Kitchen Appliances", Price = 336, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 32, Name = "Iron", Description = "Home Appliances", Price = 874, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 33, Name = "Textbook", Description = "Games", Price = 436, SupplierId = 2, CategoryId = 3 },
            new Product() { Id = 34, Name = "Monitor", Description = "Flags Products", Price = 927, SupplierId = 3, CategoryId = 3 },
            new Product() { Id = 35, Name = "Sofa", Description = "Musical Instruments", Price = 201, SupplierId = 5, CategoryId = 4 },
            new Product() { Id = 36, Name = "Cookbook", Description = "Musical Instruments", Price = 399, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 37, Name = "Egypt Flag", Description = "Kitchen Appliances", Price = 549, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 38, Name = "Laptop", Description = "Toys", Price = 442, SupplierId = 3, CategoryId = 3 },
            new Product() { Id = 39, Name = "Bed Frame", Description = "Books", Price = 657, SupplierId = 5, CategoryId = 1 },
            new Product() { Id = 40, Name = "Charger", Description = "Electronics Products", Price = 257, SupplierId = 3, CategoryId = 2 },
            new Product() { Id = 41, Name = "Tablet", Description = "Automotive Products", Price = 639, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 42, Name = "Headphones", Description = "Home Appliances", Price = 676, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 43, Name = "Dining Table", Description = "Flags Products", Price = 161, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 44, Name = "Palestine Flag", Description = "Flags Products", Price = 9, SupplierId = 1, CategoryId = 1 },
            new Product() { Id = 45, Name = "Lebanon Flag", Description = "Flags Products", Price = 10, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 46, Name = "USA Flag", Description = "Flags Products", Price = 12, SupplierId = 3, CategoryId = 3 },
            new Product() { Id = 47, Name = "China Flag", Description = "Flags Products", Price = 8, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 48, Name = "Brazil Flag", Description = "Flags Products", Price = 11, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 49, Name = "Germany Flag", Description = "Flags Products", Price = 10, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 50, Name = "France Flag", Description = "Flags Products", Price = 9, SupplierId = 2, CategoryId = 3 },
            new Product() { Id = 51, Name = "UK Flag", Description = "Flags Products", Price = 13, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 52, Name = "Russia Flag", Description = "Flags Products", Price = 9, SupplierId = 4, CategoryId = 1 },
            new Product() { Id = 53, Name = "Italy Flag", Description = "Flags Products", Price = 10, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 54, Name = "Flash Drive", Description = "Tech Gadgets", Price = 50, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 55, Name = "Notebook", Description = "Stationery", Price = 12, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 56, Name = "Wristband", Description = "Fashion Accessories", Price = 20, SupplierId = 4, CategoryId = 5 },
            new Product() { Id = 57, Name = "Palestine Flag", Description = "Flags Products", Price = 9, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 58, Name = "Portable Speaker", Description = "Tech Gadgets", Price = 40, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 59, Name = "Calendar", Description = "Office Supplies", Price = 18, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 60, Name = "Headphones", Description = "Electronics", Price = 65, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 61, Name = "Cap", Description = "Clothing and Apparel", Price = 15, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 62, Name = "Water Bottle", Description = "Travel Essentials", Price = 25, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 63, Name = "Poster", Description = "Home Decor", Price = 8, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 64, Name = "Palestine Flag", Description = "Flags Products", Price = 10, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 65, Name = "Coffee Mug", Description = "Office Supplies", Price = 15, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 66, Name = "Jordan Flag", Description = "Flags Products", Price = 8, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 67, Name = "Keychain", Description = "Fashion Accessories", Price = 5, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 68, Name = "Sunglasses", Description = "Fashion Accessories", Price = 25, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 69, Name = "T-shirt", Description = "Clothing and Apparel", Price = 18, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 70, Name = "Notebook", Description = "Stationery", Price = 12, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 71, Name = "Bracelet", Description = "Fashion Accessories", Price = 20, SupplierId = 4, CategoryId = 5 },
            new Product() { Id = 72, Name = "Laptop Sticker", Description = "Stationery", Price = 7, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 73, Name = "Pen", Description = "Office Supplies", Price = 6, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 74, Name = "Headphones", Description = "Tech Gadgets", Price = 50, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 75, Name = "Portable Speaker", Description = "Tech Gadgets", Price = 55, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 76, Name = "Water Bottle", Description = "Travel Essentials", Price = 20, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 77, Name = "Poster", Description = "Home Decor", Price = 10, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 78, Name = "Phone Case", Description = "Tech Gadgets", Price = 15, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 79, Name = "Backpack", Description = "Travel Essentials", Price = 30, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 80, Name = "Smartwatch", Description = "Tech Gadgets", Price = 80, SupplierId = 4, CategoryId = 4 },
            new Product() { Id = 81, Name = "Travel Bag", Description = "Travel Essentials", Price = 35, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 82, Name = "Power Bank", Description = "Tech Gadgets", Price = 25, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 83, Name = "Flash Drive", Description = "Tech Gadgets", Price = 10, SupplierId = 2, CategoryId = 4 },
            new Product() { Id = 84, Name = "Calendar", Description = "Office Supplies", Price = 8, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 85, Name = "Mouse Pad", Description = "Office Supplies", Price = 12, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 86, Name = "Charger", Description = "Tech Gadgets", Price = 15, SupplierId = 5, CategoryId = 5 },
            new Product() { Id = 87, Name = "Wristband", Description = "Fashion Accessories", Price = 10, SupplierId = 2, CategoryId = 1 },
            new Product() { Id = 88, Name = "Syria Flag", Description = "Flags Products", Price = 9, SupplierId = 3, CategoryId = 1 },
            new Product() { Id = 89, Name = "Umbrella", Description = "Travel Essentials", Price = 12, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 90, Name = "Lebanon Flag", Description = "Flags Products", Price = 7, SupplierId = 5, CategoryId = 1 },
            new Product() { Id = 91, Name = "Desk Organizer", Description = "Office Supplies", Price = 18, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 92, Name = "Poster", Description = "Home Decor", Price = 9, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 93, Name = "Headphones", Description = "Tech Gadgets", Price = 55, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 94, Name = "Keychain", Description = "Fashion Accessories", Price = 5, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 95, Name = "Smartwatch", Description = "Tech Gadgets", Price = 90, SupplierId = 5, CategoryId = 4 },
            new Product() { Id = 96, Name = "Pen", Description = "Office Supplies", Price = 6, SupplierId = 2, CategoryId = 2 },
            new Product() { Id = 97, Name = "Notebook", Description = "Stationery", Price = 14, SupplierId = 3, CategoryId = 1 },
            new Product() { Id = 98, Name = "Cap", Description = "Clothing and Apparel", Price = 12, SupplierId = 4, CategoryId = 2 },
            new Product() { Id = 99, Name = "Sunglasses", Description = "Fashion Accessories", Price = 25, SupplierId = 1, CategoryId = 4 },
            new Product() { Id = 100, Name = "Bracelet", Description = "Fashion Accessories", Price = 20, SupplierId = 3, CategoryId = 5 },
            new Product() { Id = 101, Name = "Phone Case", Description = "Tech Gadgets", Price = 15, SupplierId = 2, CategoryId = 3 },
            new Product() { Id = 102, Name = "Backpack", Description = "Travel Essentials", Price = 32, SupplierId = 5, CategoryId = 2 },
            new Product() { Id = 103, Name = "Water Bottle", Description = "Travel Essentials", Price = 18, SupplierId = 4, CategoryId = 3 },
            new Product() { Id = 104, Name = "Laptop Keyboard", Description = "Stationery", Price = 6, SupplierId = 1, CategoryId = 2 },
            new Product() { Id = 105, Name = "Charger", Description = "Tech Gadgets", Price = 16, SupplierId = 2, CategoryId = 5 },
            new Product() { Id = 106, Name = "Flash Drive", Description = "Tech Gadgets", Price = 12, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 107, Name = "Wristband", Description = "Fashion Accessories", Price = 11, SupplierId = 5, CategoryId = 3 },
            new Product() { Id = 108, Name = "Calendar", Description = "Office Supplies", Price = 8, SupplierId = 4, CategoryId = 1 },
            new Product() { Id = 109, Name = "Pen", Description = "Office Supplies", Price = 7, SupplierId = 1, CategoryId = 3 },
            new Product() { Id = 110, Name = "Travel Bag", Description = "Travel Essentials", Price = 36, SupplierId = 3, CategoryId = 4 },
            new Product() { Id = 111, Name = "Notebook", Description = "Stationery", Price = 13, SupplierId = 2, CategoryId = 1 },
        };
    }
}
