using KoalaInventoryManagement.Models;

namespace Inventory.Data.Data_Seeds
{
    public static class WareHousesProductsSeed
    {
        public static List<WareHouseProduct> WareHouseProducts { get; set; }
            = new List<WareHouseProduct>()
            {
                new WareHouseProduct() { ProductID = 1, WareHouseID = 3, MinStock = 7, CurrentStock = 12, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 1, WareHouseID = 5, MinStock = 7, CurrentStock = 12, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 2, WareHouseID = 1, MinStock = 9, CurrentStock = 5, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 3, WareHouseID = 5, MinStock = 12, CurrentStock = 16, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 4, WareHouseID = 2, MinStock = 8, CurrentStock = 10, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 5, WareHouseID = 3, MinStock = 15, CurrentStock = 19, MaxStock = 50 },
                new WareHouseProduct() { ProductID = 6, WareHouseID = 1, MinStock = 6, CurrentStock = 11, MaxStock = 37 },
                new WareHouseProduct() { ProductID = 7, WareHouseID = 2, MinStock = 10, CurrentStock = 18, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 8, WareHouseID = 4, MinStock = 14, CurrentStock = 22, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 9, WareHouseID = 3, MinStock = 11, CurrentStock = 15, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 10, WareHouseID = 5, MinStock = 9, CurrentStock = 13, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 11, WareHouseID = 1, MinStock = 8, CurrentStock = 14, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 12, WareHouseID = 3, MinStock = 7, CurrentStock = 9, MaxStock = 35 },
                new WareHouseProduct() { ProductID = 13, WareHouseID = 5, MinStock = 10, CurrentStock = 12, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 14, WareHouseID = 4, MinStock = 6, CurrentStock = 10, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 15, WareHouseID = 2, MinStock = 12, CurrentStock = 16, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 16, WareHouseID = 1, MinStock = 14, CurrentStock = 18, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 17, WareHouseID = 5, MinStock = 9, CurrentStock = 12, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 18, WareHouseID = 3, MinStock = 11, CurrentStock = 14, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 19, WareHouseID = 2, MinStock = 10, CurrentStock = 17, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 20, WareHouseID = 4, MinStock = 8, CurrentStock = 13, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 21, WareHouseID = 1, MinStock = 6, CurrentStock = 11, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 22, WareHouseID = 3, MinStock = 12, CurrentStock = 18, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 23, WareHouseID = 5, MinStock = 7, CurrentStock = 10, MaxStock = 36 },
                new WareHouseProduct() { ProductID = 24, WareHouseID = 2, MinStock = 15, CurrentStock = 20, MaxStock = 49 },
                new WareHouseProduct() { ProductID = 25, WareHouseID = 4, MinStock = 9, CurrentStock = 12, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 26, WareHouseID = 1, MinStock = 11, CurrentStock = 17, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 27, WareHouseID = 3, MinStock = 14, CurrentStock = 19, MaxStock = 48 },
                new WareHouseProduct() { ProductID = 28, WareHouseID = 5, MinStock = 10, CurrentStock = 13, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 29, WareHouseID = 4, MinStock = 12, CurrentStock = 16, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 30, WareHouseID = 2, MinStock = 8, CurrentStock = 12, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 31, WareHouseID = 1, MinStock = 6, CurrentStock = 2, MaxStock = 37 },
                new WareHouseProduct() { ProductID = 32, WareHouseID = 3, MinStock = 13, CurrentStock = 17, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 33, WareHouseID = 5, MinStock = 11, CurrentStock = 15, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 34, WareHouseID = 4, MinStock = 9, CurrentStock = 13, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 35, WareHouseID = 2, MinStock = 7, CurrentStock = 11, MaxStock = 35 },
                new WareHouseProduct() { ProductID = 36, WareHouseID = 1, MinStock = 12, CurrentStock = 18, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 37, WareHouseID = 3, MinStock = 10, CurrentStock = 13, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 38, WareHouseID = 5, MinStock = 9, CurrentStock = 12, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 39, WareHouseID = 4, MinStock = 11, CurrentStock = 17, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 40, WareHouseID = 2, MinStock = 8, CurrentStock = 12, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 41, WareHouseID = 1, MinStock = 6, CurrentStock = 10, MaxStock = 36 },
                new WareHouseProduct() { ProductID = 42, WareHouseID = 3, MinStock = 15, CurrentStock = 20, MaxStock = 50 },
                new WareHouseProduct() { ProductID = 43, WareHouseID = 5, MinStock = 10, CurrentStock = 9, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 44, WareHouseID = 4, MinStock = 9, CurrentStock = 12, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 45, WareHouseID = 2, MinStock = 12, CurrentStock = 18, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 46, WareHouseID = 1, MinStock = 8, CurrentStock = 13, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 47, WareHouseID = 3, MinStock = 11, CurrentStock = 14, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 48, WareHouseID = 5, MinStock = 7, CurrentStock = 9, MaxStock = 35 },
                new WareHouseProduct() { ProductID = 49, WareHouseID = 4, MinStock = 13, CurrentStock = 17, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 50, WareHouseID = 2, MinStock = 10, CurrentStock = 14, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 51, WareHouseID = 1, MinStock = 9, CurrentStock = 12, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 52, WareHouseID = 3, MinStock = 14, CurrentStock = 18, MaxStock = 48 },
                new WareHouseProduct() { ProductID = 53, WareHouseID = 5, MinStock = 11, CurrentStock = 15, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 54, WareHouseID = 1, MinStock = 8, CurrentStock = 12, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 55, WareHouseID = 4, MinStock = 6, CurrentStock = 11, MaxStock = 35 },
                new WareHouseProduct() { ProductID = 56, WareHouseID = 2, MinStock = 10, CurrentStock = 14, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 57, WareHouseID = 5, MinStock = 11, CurrentStock = 7, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 58, WareHouseID = 3, MinStock = 9, CurrentStock = 13, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 59, WareHouseID = 1, MinStock = 7, CurrentStock = 4, MaxStock = 36 },
                new WareHouseProduct() { ProductID = 60, WareHouseID = 2, MinStock = 14, CurrentStock = 19, MaxStock = 48 },
                new WareHouseProduct() { ProductID = 61, WareHouseID = 4, MinStock = 8, CurrentStock = 13, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 62, WareHouseID = 5, MinStock = 12, CurrentStock = 18, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 63, WareHouseID = 3, MinStock = 10, CurrentStock = 14, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 64, WareHouseID = 1, MinStock = 6, CurrentStock = 9, MaxStock = 34 },
                new WareHouseProduct() { ProductID = 65, WareHouseID = 4, MinStock = 13, CurrentStock = 18, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 66, WareHouseID = 2, MinStock = 9, CurrentStock = 12, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 67, WareHouseID = 3, MinStock = 15, CurrentStock = 20, MaxStock = 49 },
                new WareHouseProduct() { ProductID = 68, WareHouseID = 5, MinStock = 10, CurrentStock = 13, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 69, WareHouseID = 1, MinStock = 7, CurrentStock = 11, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 70, WareHouseID = 4, MinStock = 14, CurrentStock = 19, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 71, WareHouseID = 2, MinStock = 12, CurrentStock = 16, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 72, WareHouseID = 3, MinStock = 9, CurrentStock = 13, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 73, WareHouseID = 5, MinStock = 11, CurrentStock = 17, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 74, WareHouseID = 1, MinStock = 8, CurrentStock = 12, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 75, WareHouseID = 4, MinStock = 10, CurrentStock = 15, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 76, WareHouseID = 3, MinStock = 13, CurrentStock = 5, MaxStock = 48 },
                new WareHouseProduct() { ProductID = 77, WareHouseID = 2, MinStock = 6, CurrentStock = 10, MaxStock = 36 },
                new WareHouseProduct() { ProductID = 78, WareHouseID = 5, MinStock = 12, CurrentStock = 10, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 79, WareHouseID = 1, MinStock = 9, CurrentStock = 8, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 80, WareHouseID = 4, MinStock = 8, CurrentStock = 13, MaxStock = 41 },
                new WareHouseProduct() { ProductID = 81, WareHouseID = 3, MinStock = 7, CurrentStock = 10, MaxStock = 37 },
                new WareHouseProduct() { ProductID = 82, WareHouseID = 2, MinStock = 11, CurrentStock = 15, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 83, WareHouseID = 5, MinStock = 14, CurrentStock = 19, MaxStock = 48 },
                new WareHouseProduct() { ProductID = 84, WareHouseID = 1, MinStock = 6, CurrentStock = 9, MaxStock = 35 },
                new WareHouseProduct() { ProductID = 85, WareHouseID = 4, MinStock = 12, CurrentStock = 16, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 86, WareHouseID = 3, MinStock = 10, CurrentStock = 3, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 87, WareHouseID = 2, MinStock = 8, CurrentStock = 11, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 88, WareHouseID = 5, MinStock = 7, CurrentStock = 10, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 89, WareHouseID = 1, MinStock = 9, CurrentStock = 12, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 90, WareHouseID = 4, MinStock = 11, CurrentStock = 15, MaxStock = 44 },
                new WareHouseProduct() { ProductID = 91, WareHouseID = 3, MinStock = 13, CurrentStock = 12, MaxStock = 49 },
                new WareHouseProduct() { ProductID = 92, WareHouseID = 2, MinStock = 10, CurrentStock = 14, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 93, WareHouseID = 5, MinStock = 8, CurrentStock = 11, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 94, WareHouseID = 1, MinStock = 12, CurrentStock = 17, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 95, WareHouseID = 4, MinStock = 14, CurrentStock = 19, MaxStock = 50 },
                new WareHouseProduct() { ProductID = 96, WareHouseID = 3, MinStock = 11, CurrentStock = 16, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 97, WareHouseID = 2, MinStock = 7, CurrentStock = 10, MaxStock = 36 },
                new WareHouseProduct() { ProductID = 98, WareHouseID = 5, MinStock = 9, CurrentStock = 12, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 99, WareHouseID = 1, MinStock = 8, CurrentStock = 12, MaxStock = 40 },
                new WareHouseProduct() { ProductID = 100, WareHouseID = 4, MinStock = 6, CurrentStock = 9, MaxStock = 35 },
                new WareHouseProduct() { ProductID = 101, WareHouseID = 3, MinStock = 10, CurrentStock = 13, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 102, WareHouseID = 2, MinStock = 11, CurrentStock = 17, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 103, WareHouseID = 5, MinStock = 12, CurrentStock = 10, MaxStock = 47 },
                new WareHouseProduct() { ProductID = 104, WareHouseID = 1, MinStock = 7, CurrentStock = 10, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 105, WareHouseID = 3, MinStock = 9, CurrentStock = 14, MaxStock = 42 },
                new WareHouseProduct() { ProductID = 106, WareHouseID = 2, MinStock = 8, CurrentStock = 11, MaxStock = 38 },
                new WareHouseProduct() { ProductID = 107, WareHouseID = 4, MinStock = 10, CurrentStock = 15, MaxStock = 43 },
                new WareHouseProduct() { ProductID = 108, WareHouseID = 5, MinStock = 11, CurrentStock = 0, MaxStock = 46 },
                new WareHouseProduct() { ProductID = 109, WareHouseID = 1, MinStock = 7, CurrentStock = 12, MaxStock = 39 },
                new WareHouseProduct() { ProductID = 110, WareHouseID = 2, MinStock = 12, CurrentStock = 18, MaxStock = 45 },
                new WareHouseProduct() { ProductID = 111, WareHouseID = 3, MinStock = 9, CurrentStock = 14, MaxStock = 42 },

            };
    }
}
